#!/bin/bash

VERSION=`grep VERSION= Makefile | sed -e 's/VERSION=\(.*\)/\1/'`
if [ $1 != $VERSION ]; then
    sed -e "s/{{VERSION}}/"$1"/" Makefile.in > Makefile
    git mv css/angular.piechart-${VERSION}.css css/angular.piechart-${1}.css
    #git mv css/angular.piechart-${VERSION}.min.css css/angular.piechart-${1}.min.css
    git mv js/angular.piechart-${VERSION}.js js/angular.piechart-${1}.js
    git mv js/angular.piechart-${VERSION}.min.js js/angular.piechart-${1}.min.js
fi
